application: web-opm
version: 110
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: css
- url: /js
  static_dir: js
- url: /img
  static_dir: img
- url: /.*
  script: index.app

libraries:
- name: jinja2
  version: latest
- name: markupsafe
  version: latest
- name: setuptools
  version: latest